defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  host: localhost
  database: todo_development
  username: postgres
  password:

test:
  <<: *defaults
  database: todo_test

staging:
  <<: *defaults
  database: todo_production

production:
  <<: *defaults
  database: todo_production
